### ISSUE TITLE
Variable name not seen

### ISSUE THREAD

**Issue by sr-bentley** [roylejw/AGRF-Pacbio-scripts#1]
`filter1` is assigned but `filter` is called.

https://github.com/roylejw/AGRF-Pacbio-scripts/blob/3af5f659fd1bf0000d3ee93c4b87ab679bd50a2f/scripts/combined_16S_analysis.sh#L243-L247

**Comment by roylejw** [comment]
Oops. This is why you don’t change things the day before quitting.

I added you as a collaborator so you can fix it

**Comment by sr-bentley** [comment]
Haha not a problem. Thanks! I've merged the minor edit in
